print('merhaba')
print('adınız')
adım=str(input())
print('yaşınız')
yaşım=input()
print('bölümün')
bölüm=input()
print('nereden geldin')
gel=input()
print('nerelisin')
memleket=input()
print('tanıştığıma memnun oldum')
